[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache'
solc_version = '0.8.24'
evm_version = 'cancun'
optimizer = true
optimizer_runs = 200
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]
fs_permissions = [
    { access = "read", path = "data" },
]

# 中文注释：这里可以按需配置 RPC、Etherscan 等
