[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache'
solc_version = '0.8.24'
optimizer = true
optimizer_runs = 200
evm_version = 'cancun'
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]
fs_permissions = [
    { access = "read", path = "./data" },
    { access = "write", path = "./data" },
    { access = "read", path = "./" },
]